name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Or any other branch you want to trigger the build

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

permissions:
    contents: write
    packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      uses: docker/metadata-action@v4
      id: meta
      with:
        images: ghcr.io/${{ env.IMAGE_NAME }}
        tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}